name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Rust
      uses: hecrj/setup-rust-action@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  
  rustfmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Rust
      uses: hecrj/setup-rust-action@v1
    - name: Install Rustfmt
      run: rustup component add rustfmt
    - name: Run tests
      run: cargo fmt -- --check
      
  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Rust
      uses: hecrj/setup-rust-action@v1
    - name: Install Clippy
      run: rustup component add clippy
    - name: Run tests
      run: cargo clippy
